// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1LTdmL2bYFMDbRUeTrIrlMqM-ICkR7vI',
    appId: '1:1074018221438:web:3570d8d37cea40d898c72f',
    messagingSenderId: '1074018221438',
    projectId: 'aabis-cli',
    authDomain: 'aabis-cli.firebaseapp.com',
    storageBucket: 'aabis-cli.appspot.com',
    measurementId: 'G-WL7QQF70ZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFe1v9ZX2cH3b3SW18BWFQr6rtS13KhmE',
    appId: '1:1074018221438:android:8ee468ad2308be2898c72f',
    messagingSenderId: '1074018221438',
    projectId: 'aabis-cli',
    storageBucket: 'aabis-cli.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIE9AOeE--CtUaweCEfa1fHWMKnuJOl5w',
    appId: '1:1074018221438:ios:88dd416e5f8c20f998c72f',
    messagingSenderId: '1074018221438',
    projectId: 'aabis-cli',
    storageBucket: 'aabis-cli.appspot.com',
    iosBundleId: 'com.webnomatics.firebasePractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIE9AOeE--CtUaweCEfa1fHWMKnuJOl5w',
    appId: '1:1074018221438:ios:b63624bbee58325f98c72f',
    messagingSenderId: '1074018221438',
    projectId: 'aabis-cli',
    storageBucket: 'aabis-cli.appspot.com',
    iosBundleId: 'com.webnomatics.firebasePractice.RunnerTests',
  );
}
